Add new test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -42,7 +42,7 @@ jobs:
           directory="./src/another"
           for file in "${expected_files[@]}"; do
             if [[ ! -f "$directory/$file" ]]; then
-              echo "File $file not found" && exit 1
+              echo "File $file not found in dir $directory/$file" && ls -la $directory/$file && exit 1
             fi
           done
 
@@ -52,7 +52,7 @@ jobs:
           directory="./src/main"
           for file in "${expected_files[@]}"; do
             if [[ -f "$directory/$file" ]]; then
-              echo "File $file found" && exit 1
+              echo "File $file found in $directory/$file" && ls -la $directory/$file && exit 1
             fi
           done
       
