Update command

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -45,7 +45,7 @@ jobs:
         run: |
           cp test/file.po ${{ github.workspace }}/test/main/file.po
           cp test/file.po ${{ github.workspace }}/test/another/file.po
-          ls -la ${{ github.workspace }}/test
+          ls ${{ github.workspace }}/test
 
       - uses: ./
         with:
@@ -57,7 +57,7 @@ jobs:
           directory="./test/another"
           for file in "${expected_files[@]}"; do
             if [[ ! -f "$directory/$file" ]]; then
-              echo "File $file not found in dir $directory/$file" && ls -la $directory && exit 1
+              echo "File $file not found in dir $directory/$file" && ls $directory && exit 1
             fi
           done
 
@@ -67,7 +67,7 @@ jobs:
           directory="./test/main"
           for file in "${expected_files[@]}"; do
             if [[ -f "$directory/$file" ]]; then
-              echo "File $file found in $directory/$file" && ls -la $directory && exit 1
+              echo "File $file found in $directory/$file" && ls $directory && exit 1
             fi
           done
       
