Add new test

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -20,17 +20,38 @@ jobs:
         env:
           FILE_NAME: "src/file.po"
           FILE_DATA: ${{vars.TEMPLATE}}
-      - run: |
-          ls -la src
+
+      - name: Check create file
+        run: |
+          ls -la           
           tail src/file.po
-          rm -rf src/file.mo
+
+      - name: Create new file for build
+        run: |
+          copy src/file.po src/main/
+          copy src/file.po src/another/
+
       - uses: text-adi/build-language-i18n-action@dev
-      - name: Check Test
+        with:
+          DIR: ${{ github.workspace }}/src/another
+
+      - name: Check Test - 1
         run: |
           expected_files=("file.po" "file.mo")
-          directory="./src/"
+          directory="./src/another"
           for file in "${expected_files[@]}"; do
             if [[ ! -f "$directory/$file" ]]; then
-              echo "File $file not fount" && exit 1
+              echo "File $file not found" && exit 1
             fi
           done
+
+      - name: Check Test - 2
+        run: |
+          expected_files=("file.mo")
+          directory="./src/main"
+          for file in "${expected_files[@]}"; do
+            if [[ -f "$directory/$file" ]]; then
+              echo "File $file found" && exit 1
+            fi
+          done
+      
